# Generated by Django 3.1 on 2020-08-14 09:55

from django.db import migrations, models
import units.Upload_Byhash


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=600)),
                ('headpic', models.ImageField(null=True, upload_to=units.Upload_Byhash.to_img('headpic'))),
            ],
        ),
    ]
